# applicationset-guestbook.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-envs
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
        revision: develop
      - env: staging
        revision: main
      - env: prod
        revision: main
  template:
    metadata:
      name: 'guestbook-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/vanessakovalsky/argocd-example-apps
        targetRevision: '{{revision}}'
        path: 'bonusa/guestbook/overlays/{{env}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'guestbook-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true