# 04-notify-hook.yaml
apiVersion: batch/v1
kind: Job
metadata:

  name: notify-deploy
  namespace: guestbook
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: notify
        image: busybox
        command: ['sh', '-c', 'echo "Deployment successful! Notifying team..."']
      restartPolicy: Never